## 第一部分：基础信息
name: loongson1c                                    # <必选项> 包名称 （符合C语言变量命名规则），长度少于等于64字节
version: master                                     # <必选项> 组件版本号
description: SoC Loongson1C                         # <必选项> 建议至少20字以上
type: chip                                          # <必选项> 组件类型，为：solution, chip, board, common, sdk

tag: 核心模块                                       # <可选项> 组件分类，缺省值： ''
keywords:                                           # <可选项> 标签，会影响到组件被搜索的效果，合理的标签很重要
  - base
license: Apache license v2.0                        # <可选项> 源代码的许可证，要确保所有代码、文件的许可证不冲突。如：MIT，Apache license v2.0，BSD

#           指定该组件依赖的组件及版本，版本支持条件比较，支持：>=v1.0, >v1.0, ==v1.0, <=v1.0, <v1.0, v1.0
#           未指定条件时，默认为 ==，如 v1.0 与 ==v1.0
# depends:                                 # <可选项> 该组件依赖其他的组件，合理的依赖才能保证组件能编译、使用
#   - minilibc: v7.2.0
#   - aos: >=v7.2.0
depends:
  - mips: master
  - libc_stub: master
  - osal_aos: master
  - init: master
  - lwip: master
  - uart: master
  - debug: master
  - cli: master
  - kv: master

## 第四部分：编译连接信息
# build_config:                            # <可选项> 编译配置项
#   include:                               # <可选项> 编译时，影响编译器的-I 参数 ,全局有效
#     - src                                #        include 只能是该软件包下的目录，不能使用外部目录
#   internal_include:                      # <可选项> 编译时，影响编译器的-I 参数 ,组件内有效
#     - include
#   cflag: ''                              # <可选项> C 编译器所需要要的编译参数
#   cxxflag: ''                            # <可选项> CXX 编译器所需要要的编译参数
#   asmflag: ''                            # <可选项> 汇编器所需要要参数
#   define:                                # <可选项> 宏定义, 增加编译器的-D 选项,如：
#     XXX: 1                               #   -DXXX=1
#     AAA: 1                               #   -DAAA
#     STR: "abc"                           #   -DSTR="abc"
#   libs:                                  # 该组件中支持的二进制静态库,如：libxxx.a, libyyy.a
#     - xxx                                #   -lxxx
#     - yyy                                #   -lyyy
#   libpath:                               # 指定静态库所在的路径（相对于该组件路径）
#     - libs                               #   -Llibs
build_config:
  cflag: -mips32 -EL -msoft-float -mfp32 -mno-abicalls -fno-pic -ffunction-sections -fdata-sections -G0 -fno-builtin -std=gnu99 -g -Wall -O0
  cxxflag: -mips32 -EL -msoft-float -mfp32 -mno-abicalls -fno-pic -ffunction-sections -fdata-sections -G0 -fno-builtin -std=gnu99 -g -Wall -O0
  asmflag: -mips32 -EL -msoft-float -mfp32 -mno-abicalls -fno-pic -G0 -fno-builtin -Wall -D__ASSEMBLY__
  ldflag: -v -mips32 -EL -msoft-float -mfp32
  postimage_script:

  include:
    - include
    - aos_adapter
    - aos_adapter/arch
    - vendor_sdk/openloongsonlib1c

  internal_include:

# source_file:                             # <可选项> 指定参与编译的源代码文件，支持通配符，采用相对路径
#   - src/*.c                              # 例：组件 src 目录下所有的扩展名为 c 的源代码文件
source_file:
  - "aos_adapter/soc_impl.c"
  - "aos_adapter/libc.c"
  - "aos_adapter/dirent.c"
  - "aos_adapter/fs.c"
  - "aos_adapter/hal/uart.c"
  - "aos_adapter/ethernet/synopGMAC.c"
  - "aos_adapter/ethernet/synopGMAC_Dev.c"
  - "aos_adapter/ethernet/synopGMAC_plat.c"
  - "vendor_sdk/openloongsonlib1c/*.c"
  - "vendor_sdk/openloongsonlib1c/*.S"

## 第五部分：配置信息
# def_config:                              # 组件的可配置项
#   CONFIG_DEBUG: y
#   CONFIG_PARAM_NOT_CHECK: y
#   CONFIG_CLI: y

def_config:
  TOOLCHAIN_SDE: 1
  WITH_LWIP: 1
  CONFIG_LWIP_VERSION: "lwip2.0.0"
  CONFIG_LWIP_V200: y
  POSIX_DEVICE_IO_NEED: 1
  CLI_CONFIG_STACK_SIZE: 8192
  CLI_IOBOX_ENABLE: 1
  HAL_UART_STDIO_PORT: 2
  CONFIG_U_UART_DEV: 0
  AOS_USING_GMAC_INT_MODE: 1

chip:
  arch_name: mips
  cpu_name: ls232
  vendor_name: Loongson
  ld_script: loongson1c.ld

hw_info:
  arch_name: mips
  cpu_name: ls232
  toolchain_prefix: mips-sde-elf
  vendor_name: Loongson
  ld_script: loongson1c.ld
  flash_program:

## 第六部分：安装信息
# install:
#   - dest: include/                       # 安装的目的路径 dest是相当路径，通常是相对于YoC SDK 安装目录
#     source:                              # 安装源列表
#      - src/*.h                           # 支持通配符，相对路径

## 第七部分：导出部分
# export:
#   - dest: "<SOLUTION_PATH>/generated/data" # 安装的目的路径 dest是相当路径
#     source:                                # 安装源列表
#       - "bootimgs/boot"
#       - "bootimgs/tee"
#       - "bootimgs/mtb"
#       - "configs/config.yaml"
